Mode = "dev" # Not read in code anywhere yet?

[sisu]
keyring-backend = "test"
chain-id = "tbd"
api-host = "0.0.0.0" # Not read in code anywhere yet?
api-port = 25456

[tss]
dheart-host = "dheart"
dheart-port = 5678
