---
apiVersion: v1
kind: Service
metadata:
  name: deyes
spec:
  ports:
  - name: tcp-deyes
    port: 31001
    protocol: TCP
    targetPort: 31001
  selector:
    app: deyes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deyes
  labels:
    app: deyes
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: deyes
  template:
    metadata:
      labels:
        app: deyes
    spec:
      containers:
      - command:
          - deyes
        workingDir: /root
        image: sisu.test/sisu-all:latest
        imagePullPolicy: IfNotPresent
        name: deyes
        env:
          - name: HOME_DIR
            value: /root
        ports:
          - containerPort: 31001
            name: tcp-deyes
