enable = true
dheart_host = "dheart"
dheart_port = 5678
[supported_chains]
[supported_chains.eth]
  symbol = "eth"
  id = 1
  deyes_url = "http://deyes:31001"
[supported_chains.sisu-eth]
  symbol = "sisu-eth"
  id = 36767
  deyes_url = "http://deyes:31001"
