db_host = "localhost"
db_port = 3306
db_username = "root"
db_password = "password"
db_schema = "deyes"

server_port = 31001
sisu_server_url = "http://0.0.0.0:25456"

use_external_rpcs_info = false

[log_dna]
secret = ""
app_name = ""
host_name = ""
flush_interval = "0s"
max_buffer_len = 0
log_local = false

[chains]
[chains.ganache1]
  chain = "ganache1"
  block_time = 3000
  adjust_time = 300
  starting_block = 0
  rpcs = ["http://localhost:7545", ]
  wss = []
	use_eip_1559 = false
  rpc_secret = ""
  client_type = ""
  solana_bridge_program_id=""
[chains.ganache2]
  chain = "ganache2"
  block_time = 3000
  adjust_time = 300
  starting_block = 0
  rpcs = ["http://localhost:8545", ]
  wss = []
	use_eip_1559 = false
  rpc_secret = ""
  client_type = ""
  solana_bridge_program_id=""

[tokens]
[tokens.ETH]
  symbol = "ETH"
  coin_cap_name = "ethereum"
  coin_gecko_name = "ethereum"
[tokens.AVAX]
  symbol = "AVAX"
  coin_cap_name = "avalanche-2"
[tokens.BNB]
  symbol = "BNB"
  coin_cap_name = "binance-coin"
  coin_gecko_name = "binancecoin"
[tokens.FTM]
  symbol = "FTM"
  coin_cap_name = "fantom"
  coin_gecko_name = "fantom"
[tokens.MATIC]
  symbol = "MATIC"
  coin_cap_name = "polygon"
  coin_gecko_name = "matic-network"
[tokens.ADA]
  symbol = "ADA"
  coin_cap_name = "cardano"
  coin_gecko_name = "cardano"
[tokens.SOL]
  symbol = "SOL"
  coin_cap_name = "solana"
  coin_gecko_name = "solana"
[tokens.LSK]
  symbol = "LSK"
  coin_cap_name = "lisk"
  coin_gecko_name = "lisk"
