// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sisu/chain_metadata.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ChainMetadata struct {
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Chain  string `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	// Used for solana
	SolanaRecentBlockHash   string `protobuf:"bytes,3,opt,name=solanaRecentBlockHash,proto3" json:"solanaRecentBlockHash,omitempty"`
	SolanaRecentBlockHeight int64  `protobuf:"varint,4,opt,name=solanaRecentBlockHeight,proto3" json:"solanaRecentBlockHeight,omitempty"`
}

func (m *ChainMetadata) Reset()         { *m = ChainMetadata{} }
func (m *ChainMetadata) String() string { return proto.CompactTextString(m) }
func (*ChainMetadata) ProtoMessage()    {}
func (*ChainMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f015573824c9627, []int{0}
}
func (m *ChainMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChainMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChainMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChainMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainMetadata.Merge(m, src)
}
func (m *ChainMetadata) XXX_Size() int {
	return m.Size()
}
func (m *ChainMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_ChainMetadata proto.InternalMessageInfo

func (m *ChainMetadata) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *ChainMetadata) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *ChainMetadata) GetSolanaRecentBlockHash() string {
	if m != nil {
		return m.SolanaRecentBlockHash
	}
	return ""
}

func (m *ChainMetadata) GetSolanaRecentBlockHeight() int64 {
	if m != nil {
		return m.SolanaRecentBlockHeight
	}
	return 0
}

type UpdateSolanaRecentHash struct {
	Signer string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Chain  string `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	Hash   string `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Height int64  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *UpdateSolanaRecentHash) Reset()         { *m = UpdateSolanaRecentHash{} }
func (m *UpdateSolanaRecentHash) String() string { return proto.CompactTextString(m) }
func (*UpdateSolanaRecentHash) ProtoMessage()    {}
func (*UpdateSolanaRecentHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f015573824c9627, []int{1}
}
func (m *UpdateSolanaRecentHash) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateSolanaRecentHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateSolanaRecentHash.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UpdateSolanaRecentHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSolanaRecentHash.Merge(m, src)
}
func (m *UpdateSolanaRecentHash) XXX_Size() int {
	return m.Size()
}
func (m *UpdateSolanaRecentHash) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSolanaRecentHash.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSolanaRecentHash proto.InternalMessageInfo

func (m *UpdateSolanaRecentHash) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *UpdateSolanaRecentHash) GetChain() string {
	if m != nil {
		return m.Chain
	}
	return ""
}

func (m *UpdateSolanaRecentHash) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *UpdateSolanaRecentHash) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type UpdateSolanaRecentHashMsg struct {
	Signer string                  `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Data   *UpdateSolanaRecentHash `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *UpdateSolanaRecentHashMsg) Reset()         { *m = UpdateSolanaRecentHashMsg{} }
func (m *UpdateSolanaRecentHashMsg) String() string { return proto.CompactTextString(m) }
func (*UpdateSolanaRecentHashMsg) ProtoMessage()    {}
func (*UpdateSolanaRecentHashMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_5f015573824c9627, []int{2}
}
func (m *UpdateSolanaRecentHashMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateSolanaRecentHashMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateSolanaRecentHashMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UpdateSolanaRecentHashMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSolanaRecentHashMsg.Merge(m, src)
}
func (m *UpdateSolanaRecentHashMsg) XXX_Size() int {
	return m.Size()
}
func (m *UpdateSolanaRecentHashMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSolanaRecentHashMsg.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSolanaRecentHashMsg proto.InternalMessageInfo

func (m *UpdateSolanaRecentHashMsg) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *UpdateSolanaRecentHashMsg) GetData() *UpdateSolanaRecentHash {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ChainMetadata)(nil), "types.ChainMetadata")
	proto.RegisterType((*UpdateSolanaRecentHash)(nil), "types.UpdateSolanaRecentHash")
	proto.RegisterType((*UpdateSolanaRecentHashMsg)(nil), "types.UpdateSolanaRecentHashMsg")
}

func init() { proto.RegisterFile("sisu/chain_metadata.proto", fileDescriptor_5f015573824c9627) }

var fileDescriptor_5f015573824c9627 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0xce, 0x2c, 0x2e,
	0xd5, 0x4f, 0xce, 0x48, 0xcc, 0xcc, 0x8b, 0xcf, 0x4d, 0x2d, 0x49, 0x4c, 0x49, 0x2c, 0x49, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0xa9, 0x2c, 0x48, 0x2d, 0x56, 0x5a, 0xcb, 0xc8,
	0xc5, 0xeb, 0x0c, 0x92, 0xf7, 0x85, 0x4a, 0x0b, 0x89, 0x71, 0xb1, 0x15, 0x67, 0xa6, 0xe7, 0xa5,
	0x16, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x79, 0x42, 0x22, 0x5c, 0xac, 0x60, 0x83,
	0x24, 0x98, 0xc0, 0xc2, 0x10, 0x8e, 0x90, 0x09, 0x97, 0x68, 0x71, 0x7e, 0x4e, 0x62, 0x5e, 0x62,
	0x50, 0x6a, 0x72, 0x6a, 0x5e, 0x89, 0x53, 0x4e, 0x7e, 0x72, 0xb6, 0x47, 0x62, 0x71, 0x86, 0x04,
	0x33, 0x58, 0x15, 0x76, 0x49, 0x21, 0x0b, 0x2e, 0x71, 0x4c, 0x89, 0xd4, 0xcc, 0xf4, 0x8c, 0x12,
	0x09, 0x16, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0x5c, 0xd2, 0x4a, 0x45, 0x5c, 0x62, 0xa1, 0x05, 0x29,
	0x89, 0x25, 0xa9, 0xc1, 0x48, 0x0a, 0xc0, 0x66, 0x92, 0xe6, 0x6e, 0x21, 0x2e, 0x96, 0x0c, 0x84,
	0x33, 0xc1, 0x6c, 0x90, 0x09, 0x19, 0xc8, 0x8e, 0x80, 0xf2, 0x94, 0xd2, 0xb8, 0x24, 0xb1, 0xdb,
	0xe9, 0x5b, 0x9c, 0x8e, 0xd3, 0x5a, 0x43, 0x2e, 0x16, 0x50, 0x70, 0x82, 0x6d, 0xe5, 0x36, 0x92,
	0xd5, 0x03, 0x07, 0xb7, 0x1e, 0x76, 0x73, 0x82, 0xc0, 0x4a, 0x9d, 0x9c, 0x4f, 0x3c, 0x92, 0x63,
	0xbc, 0xf0, 0x48, 0x8e, 0xf1, 0xc1, 0x23, 0x39, 0xc6, 0x09, 0x8f, 0xe5, 0x18, 0x2e, 0x3c, 0x96,
	0x63, 0xb8, 0xf1, 0x58, 0x8e, 0x21, 0x4a, 0x33, 0x3d, 0xb3, 0x24, 0xa3, 0x34, 0x49, 0x2f, 0x39,
	0x3f, 0x57, 0x1f, 0x14, 0xa5, 0xba, 0x79, 0xa9, 0x25, 0xe5, 0xf9, 0x45, 0xd9, 0x60, 0x8e, 0x7e,
	0x05, 0x84, 0x02, 0xdb, 0x90, 0xc4, 0x06, 0x8e, 0x5e, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x6f, 0x02, 0x45, 0x8f, 0xfb, 0x01, 0x00, 0x00,
}

func (m *ChainMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChainMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ChainMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SolanaRecentBlockHeight != 0 {
		i = encodeVarintChainMetadata(dAtA, i, uint64(m.SolanaRecentBlockHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.SolanaRecentBlockHash) > 0 {
		i -= len(m.SolanaRecentBlockHash)
		copy(dAtA[i:], m.SolanaRecentBlockHash)
		i = encodeVarintChainMetadata(dAtA, i, uint64(len(m.SolanaRecentBlockHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Chain) > 0 {
		i -= len(m.Chain)
		copy(dAtA[i:], m.Chain)
		i = encodeVarintChainMetadata(dAtA, i, uint64(len(m.Chain)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintChainMetadata(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UpdateSolanaRecentHash) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateSolanaRecentHash) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UpdateSolanaRecentHash) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintChainMetadata(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintChainMetadata(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Chain) > 0 {
		i -= len(m.Chain)
		copy(dAtA[i:], m.Chain)
		i = encodeVarintChainMetadata(dAtA, i, uint64(len(m.Chain)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintChainMetadata(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *UpdateSolanaRecentHashMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateSolanaRecentHashMsg) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UpdateSolanaRecentHashMsg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Data != nil {
		{
			size, err := m.Data.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintChainMetadata(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintChainMetadata(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintChainMetadata(dAtA []byte, offset int, v uint64) int {
	offset -= sovChainMetadata(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ChainMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovChainMetadata(uint64(l))
	}
	l = len(m.Chain)
	if l > 0 {
		n += 1 + l + sovChainMetadata(uint64(l))
	}
	l = len(m.SolanaRecentBlockHash)
	if l > 0 {
		n += 1 + l + sovChainMetadata(uint64(l))
	}
	if m.SolanaRecentBlockHeight != 0 {
		n += 1 + sovChainMetadata(uint64(m.SolanaRecentBlockHeight))
	}
	return n
}

func (m *UpdateSolanaRecentHash) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovChainMetadata(uint64(l))
	}
	l = len(m.Chain)
	if l > 0 {
		n += 1 + l + sovChainMetadata(uint64(l))
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovChainMetadata(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovChainMetadata(uint64(m.Height))
	}
	return n
}

func (m *UpdateSolanaRecentHashMsg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovChainMetadata(uint64(l))
	}
	if m.Data != nil {
		l = m.Data.Size()
		n += 1 + l + sovChainMetadata(uint64(l))
	}
	return n
}

func sovChainMetadata(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozChainMetadata(x uint64) (n int) {
	return sovChainMetadata(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ChainMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChainMetadata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChainMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChainMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChainMetadata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChainMetadata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChainMetadata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChainMetadata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SolanaRecentBlockHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChainMetadata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChainMetadata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SolanaRecentBlockHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SolanaRecentBlockHeight", wireType)
			}
			m.SolanaRecentBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SolanaRecentBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipChainMetadata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthChainMetadata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateSolanaRecentHash) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChainMetadata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateSolanaRecentHash: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateSolanaRecentHash: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChainMetadata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChainMetadata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Chain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChainMetadata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChainMetadata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Chain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChainMetadata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChainMetadata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipChainMetadata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthChainMetadata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateSolanaRecentHashMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChainMetadata
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateSolanaRecentHashMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateSolanaRecentHashMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthChainMetadata
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthChainMetadata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChainMetadata
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChainMetadata
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthChainMetadata
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Data == nil {
				m.Data = &UpdateSolanaRecentHash{}
			}
			if err := m.Data.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipChainMetadata(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthChainMetadata
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipChainMetadata(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowChainMetadata
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChainMetadata
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChainMetadata
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthChainMetadata
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupChainMetadata
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthChainMetadata
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthChainMetadata        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowChainMetadata          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupChainMetadata = fmt.Errorf("proto: unexpected end of group")
)
