package flags

const (
	RootFolder = "root-folder"

	Chain               = "chain"
	Name                = "name"
	Index               = "index"
	Chains              = "chains"
	Erc20Addr           = "erc20-addr"
	Erc20Addrs          = "erc20-addrs"
	Erc20Name           = "erc20-name"
	Erc20Names          = "erc20-names"
	Erc20Symbol         = "erc20-symbol"
	Erc20Symbols        = "erc20-symbols"
	ExpectedAddrs       = "expected-addrs"
	ExpectedVaultAddrs  = "expected-vault-addrs"
	VaultAddrs          = "vault-addrs"
	ExpectedErc20Addrs  = "expected-erc20-addrs"
	ChainUrl            = "chain-url"
	ChainUrls           = "chain-urls"
	SisuRpc             = "sisu-rpc"
	Amount              = "amount"
	NewOwner            = "new-owner"
	NewLiquidityAddress = "new-liquidity-address"
	Contract            = "contract"
	Mnemonic            = "mnemonic"
	ContractHash        = "contract-hash"
	Tokens              = "tokens"
	Account             = "account"
	Recipient           = "recipient"
	Src                 = "src"
	SrcUrl              = "src-url"
	Dst                 = "dst"
	GenesisFolder       = "genesis-folder"
	KeyringBackend      = "keyring-backend"
	Algo                = "algo"
	MinimumGasPrices    = "minimum-gas-prices"
	CardanoChain        = "cardano-chain"
	CardanoSecret       = "cardano-secret"
	CardanoMnemonic     = "cardano-mnemonic"
	CardanoDbConfig     = "cardano-db-config"
	DeyesApiUrl         = "deyes-api-url"
	EnabledNonEvmChains = "enabled-non-evm-chains"
)
