# This is a basic workflow that is manually triggered

name: sisu

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request]

# This workflow makes x86_64 binaries for mac, windows, and linux.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Setting go
        run: git config core.ignorecase true && git config --global url."https://${{ secrets.ACCESS_TOKEN }}:@github.com".insteadOf "https://github.com"

      - name: Download dependencies
        env:
          GO111MODULE: on
          GOSUMDB: off
        run: go mod download

      - name: Compile
        run: |
          go build cmd/sisud/main.go
      - name: Unit test
        run: make test
