# This is a basic workflow that is manually triggered

name: sisu

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request]

# This workflow makes x86_64 binaries for mac, windows, and linux.

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
        targetos: [windows, darwin, linux]
    name: sisu ${{ matrix.arch }} for ${{ matrix.targetos }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        env:
          GOOS: ${{ matrix.targetos }}
          GOARCH: ${{ matrix.arch }}

      - name: Setting go
        run: git config --global url."https://${{ secrets.ACCESS_TOKEN }}:@github.com".insteadOf "https://github.com"

      - name: Download dependencies
        env:
          GO111MODULE: on
          GOPROXY: direct
#          GOSUMDB: off
        run: go mod download

      - name: Compile
        run: |
          cd cmd/sisud
          go build .

      - uses: actions/upload-artifact@v2
        with:
          name: sisud ${{ matrix.targetos }} ${{ matrix.arch }}
          path: cmd/sisud/sisud
